include: package:pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    camel_case_types: true
analyzer:
  errors:
    todo: ignore
#   exclude:
#     - path/to/excluded/files/**
