name: advent_of_code_21
description: Solutions to the advent of code 2021 problems.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
